routes/web.php
   Route::get('/admin/login','AdminController@index'); // admin login view
   Route::post('admin/login-post','AdminController@loginPost'); // admin login
	Route::resource('register','RegisterController');  // register module with resource
   Route::get("activate/{email}/{activationCode}", 'RegisterController@activate'); // Register mail
   Route::resource('forgot','ForgotController'); // forgot Password
<<<<<<< HEAD
   Route::post('supplier/forgot','ForgotController@storesupplier'); // forgot Password

	Route::get('reset/{email}/{code}','ForgotController@show'); // reset password
    Route::get('terms_and_condition','LoginController@termsandcondition'); // terms and condition
    Route::get('back-to-admin','AdminController@backtoadmin'); // terms and condition

    Route::get('state/{id}','RegisterController@state');

    Route::get('city/{id}','RegisterController@city');

=======
	Route::get('reset/{email}/{code}','ForgotController@show'); // reset password 
>>>>>>> a4c94b4ecea0498d6873d20ed433a1495e86c9dc

});


/**
Admin
 **/
Route::group(['middleware' => 'admin'], function() { 
 
   /* Admin Manage profile */ 
   Route::get('admin/dashboard','AdminController@dashboard'); 
   Route::get('admin/users','AdminController@users'); 
   Route::get('admin/supplier','AdminController@supplier'); 
   Route::get('admin/profile','AdminController@profile'); 
 
   /* Admin Manage own profile */ 
<<<<<<< HEAD
   Route::post('profile/{id}', array('as' => 'admin.updateProfile', 'uses' => 'ProfileController@updateProfileadmin'));     
=======
   Route::post('profile/{id}', array('as' => 'admin.updateProfile', 'uses' => 'ProfileController@updateProfile'));     
>>>>>>> a4c94b4ecea0498d6873d20ed433a1495e86c9dc
   Route::get('admin/changePass','AdminController@changePass');
   Route::post('update-password/{id}',['as'=>'password.update','uses'=>'ProfileController@updatePassword']);
   Route::get('changeUserStatus/{user_id}/{status}', ['as'=>'user.status.change','uses'=>'AdminController@changeUserStatus']);

   /* Admin Manage update profile (user & supplier ) */ 
   Route::get('showUserProfile/{id}','AdminController@showUserProfile');  
   Route::post('updateUserProfile/{id}','AdminController@updateUserProfile'); 
  
   /* Admin Manage Login (user & supplier) */ 
   Route::get('userLogin/{id}','AdminController@userLogin');  
   Route::get('supplierLogin/{id}','AdminController@supplierLogin'); 

   /* Admin Export User & supp Data */
   Route::get('user/export', 'AdminController@userExport');
   Route::get('supplier/export', 'AdminController@supplierExport');
  
   /* Admin Manage User & supplier delete */
   Route::get('userIsDelete/{user_id}/{status}','AdminController@userIsDelete');
  
   /* Admin Manage Flight */
   Route::resource('admin-flight','FlightController');  
   Route::get('flightStatus/{flight_id}/{status}','FlightController@flightStatus');
   Route::get('flightsIsDelete/{flight_id}/{status}','FlightController@flightIsDelete');
  
   /* Admin Manage Source */
   Route::resource('admin-flightSource','FlightSourceController');
   Route::get('flightSourceStatus/{flight_id}/{status}','FlightSourceController@flightSourceStatus');
   Route::get('flightSourceIsDelete/{flight_id}/{status}','FlightSourceController@flightSourceIsDelete');
  
   /* Admin Manage Destination */
   Route::resource('admin-flightDestination','FlightDestinationController');
   Route::get('flightDestinationStatus/{flight_id}/{status}','FlightDestinationController@flightDestinationStatus');
   Route::get('flightDestinationIsDelete/{flight_id}/{status}','FlightDestinationController@flightDestinationIsDelete');
  
   /* Admin Manage Country */
   Route::resource('admin-country','CountryController');
   Route::get('countryStatus/{country_id}/{status}','CountryController@countryStatus');
   Route::get('countryIsDelete/{country_id}/{status}','CountryController@countryIsDelete');
  
   /* Admin Manage State */
   Route::resource('admin-state','StateController');
   Route::get('stateStatus/{state_id}/{status}','StateController@stateStatus');
   Route::get('stateIsDelete/{state_id}/{status}','StateController@stateIsDelete');
  
   /* Admin Manage City */
   Route::resource('admin-city','CityController');
   Route::get('cityStatus/{city_id}/{status}','CityController@cityStatus');
   Route::get('cityIsDelete/{state_id}/{status}','CityController@cityIsDelete');
  
   /* Admin Manage One Way Flight */
   Route::get('admin/oneWayFlights','FlightOneWayController@listOneWayFlight');
   Route::get('admin/createOneWayFlight','FlightOneWayController@createOneWayFlight');
   Route::post('storeFlightOneWay','FlightOneWayController@storeFlightOneWay');
   Route::get('admin/flightIsDelete/{flight_id}/{status}','FlightOneWayController@flightIsDelete');
   Route::get('changeFlightStatus/{flight_id}/{status}','FlightOneWayController@changeFlightStatus');
   Route::get('editOneWayFlight/{id}','FlightOneWayController@editOneWayFlight');
   Route::post('updateOneWayFlight/{id}','FlightOneWayController@updateOneWayFlight');
   Route::post('admin-flightOneWay-destroy','FlightOneWayController@destroy');
  
   /* Admin Manage Round Trip Flight */
   Route::get('admin/roundTripFlights','FlightRoundTripController@listRoundTripFlight');
   Route::get('admin/createRoundTripFlight','FlightRoundTripController@createRoundTripFlight');
   Route::post('storeRoundTripFlight','FlightRoundTripController@storeFlightRoundTrip');
   Route::get('admin/roundflightIsDelete/{flight_id}/{status}','FlightRoundTripController@flightIsDelete');
   Route::get('changeRoundFlightStatus/{flight_id}/{status}','FlightRoundTripController@changeFlightStatus');
   Route::get('editRoundTripFlight/{id}','FlightRoundTripController@editRoundTripFlight');
   Route::post('updateRoundTripFlight/{id}','FlightRoundTripController@updateRoundTripFlight');
   Route::post('admin-flightRoundTrip-destroy','FlightRoundTripController@destroy');

   /* Admin Manage Multi City Flight */
   Route::get('admin/multiCityFlights','FlightMultiCityController@listMultiCityFlight');
   Route::get('admin/createMultiCityFlight','FlightMultiCityController@createMultiCityFlight');
   Route::post('storeMultiCityFlight','FlightMultiCityController@storeFlightMultiCity');
   Route::get('admin/multiCityflightIsDelete/{flight_id}/{status}','FlightMultiCityController@flightIsDelete');
   Route::get('changeMultiCityFlightStatus/{flight_id}/{status}','FlightMultiCityController@changeFlightStatus');
   Route::get('editMultiCityFlight/{id}','FlightMultiCityController@editMultiCityFlight');
   Route::post('updateMultiCityFlight/{id}','FlightMultiCityController@updateMultiCityFlight');

   /* add balance for user */
   Route::post('add_balance','AdminController@add_balance');
   Route::get('delete_balance/{id}','AdminController@delete_balance');
   Route::get('admin/transaction-history','AdminTransactionhistoryController@balancehistory');
<<<<<<< HEAD

    Route::get('admin_history','AdminController@userbookinghistory');

    Route::get('admin/delete/OneWayFlights','AdminController@OneWayFlights');
    Route::get('admin/delete/RoundTripFlights','AdminController@RoundTripFlights');
    Route::get('admin/delete/MultiCityFlights','AdminController@MultiCityFlights');

=======
>>>>>>> a4c94b4ecea0498d6873d20ed433a1495e86c9dc
});

/** 
User
**/
Route::group(['middleware' => 'user'], function() {

   /* user Manage own profile */
<<<<<<< HEAD
       Route::get('user/dashboard','UserController@index');
       Route::get('user/profile','UserController@profile');
       Route::get('user/changePass','UserController@changePass');
       Route::post('user/profile/{id}', 'ProfileController@updateProfile');
       Route::post('user/update-password/{id}','ProfileController@updatePassword');
   
   /* user Manage One Way Flight */
       Route::post('flights/one-way-search','OnewayFlightsController@onewaysearch');
       Route::post('flights/one-way-book','OnewayFlightsController@bookoneway');
       Route::get('flights/checkout_one_way','OnewayFlightsController@checkoutoneway');
       Route::get('flights/emailoneway','MailsendController@emailoneway');
       Route::post('flights/payment','OnewayFlightsController@paymentoneway');//one way payment


   /* user Manage Round Trip Flight */
       Route::post('flights/round-trip-search','RoundTripFlightsController@roundTripsearch');
       Route::post('flights/round-trip-book','RoundTripFlightsController@bookroundtrip');
       Route::get('flights/emailroundtrip','MailsendController@emailroundtrip');
       Route::post('flights/payment/roundtrip','RoundTripFlightsController@paymentroundtrip');//one way payment


    /* user Manage multi city Flight */
        Route::post('flights/multi-city-search','MultiCityFlightsController@multicitysearch');
        Route::post('flights/multi-city-book','MultiCityFlightsController@bookmulticity');
        Route::get('flights/emailmulticity','MailsendController@emailmulticity');
        Route::post('flights/payment/multicity','MultiCityFlightsController@paymentmulticity');//one way payment

        Route::get('payu','UserController@payu');

        Route::get('history','UserController@userhistory');
        Route::post('sendemail','UserController@emailsend');
=======
   Route::get('user/dashboard','UserController@index');
   Route::get('user/profile','UserController@profile');
   Route::get('user/changePass','UserController@changePass');
   Route::post('user/profile/{id}', 'ProfileController@updateProfile');
   Route::post('user/update-password/{id}','ProfileController@updatePassword');
   
   /* user Manage One Way Flight */
   Route::post('flights/one-way-search','OnewayFlightsController@onewaysearch');
   Route::post('flights/one-way-book','OnewayFlightsController@bookoneway');
   Route::get('flights/checkout_one_way','OnewayFlightsController@checkoutoneway');
   Route::get('flights/emailoneway','MailsendController@emailoneway');


   /* user Manage Round Trip Flight */

app/Models/FlightDestination.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FlightDestination extends Model
{
    //
}

app/Http/Controllers/FlightDestinationController.php
<?php

namespace App\Http\Controllers;

use App\Models\FlightDestination;
use Illuminate\Http\Request;

class FlightDestinationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
<<<<<<< HEAD
        $flight=FlightDestination::where('is_delete','1')->orderBy('id', 'desc')->get();
=======
        $flight=FlightDestination::where('is_delete','1')->get();
>>>>>>> a4c94b4ecea0498d6873d20ed433a1495e86c9dc
        return view('admin.flightDestination.index',compact('flight'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.flightDestination.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'flight_destination' =>'required|unique:flight_destinations'
        ]);

        $flight = new  FlightDestination;
        $flight->flight_destination=$request->flight_destination;
        $flight->save();
        return redirect()->route('admin-flightDestination.index')->with(['success'=>'Flight Destination added successfully']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\FlightDestination  $flightDestination
     * @return \Illuminate\Http\Response
     */
    public function show(FlightDestination $flightDestination)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\FlightDestination  $flightDestination
     * @return \Illuminate\Http\Response
     */
    public function edit(FlightDestination $flightDestination,$id)
    {
        $flight=FlightDestination::where('id',$id)->first();
        return view('admin.flightDestination.edit',compact('flight'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\FlightDestination  $flightDestination
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FlightDestination $flightDestination,$id)
    {
        $this->validate($request,[
            'flight_destination' =>'required'
        ]);
        $flight = FlightDestination::find($id);
        $flight->flight_destination=$request->flight_destination;
        $flight->save();
        return redirect()->route('admin-flightDestination.index')->with(['success'=>'Flight Destination Updated successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FlightDestination  $flightDestination
     * @return \Illuminate\Http\Response
     */
    public function destroy(FlightDestination $flightDestination)
    {
        //
    }

    public function flightDestinationStatus($flight_id,$status)
    {
         FlightDestination::where('id',$flight_id)->update(['status'=>$status]);
         return redirect()->back()->with(['success' => 'Flight status updated successfully.']);
    }

    public function flightDestinationIsDelete($flight_id,$status)
    {
         FlightDestination::where('id',$flight_id)->update(['is_delete'=>$status]);
         return redirect()->back()->with(['success' => 'Deleted successfully.']);
    }
}

resources/views/admin/flightDestination/create.blade.php
@extends('adminlayouts.dashMaster')
@section('title') Admin | Add Flights Destination @endsection
@section('style')
@endsection
@section('content')
<meta name="csrf_token"  content="{{ csrf_token() }}" />
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                Flight Destination
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Flight Destination
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        
        <div class="row">
            <div class="col-md-6">
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    <!--begin::Form-->
                    <form class="m-form m-form--fit m-form--label-align-right" action="{{route('admin-flightDestination.store')}}" method="post" >
                        <div class="m-portlet__body">
                            <input type="hidden" name="_token" id="_token" value="{{csrf_token()}}">
                            <div class="form-group m-form__group">
                                <label for="exampleInputEmail1">
                                    Flight Destination Name<span class="m--font-danger"> *</span>

                                </label>
                                <input type="text" class="form-control m-input" autocomplete="off" id="exampleInputText" name="flight_destination"  placeholder="Enter Flight Destination">
                                 @if ($errors->has('flight_destination'))
                                                <span class="help-block text-danger">
                                                    <strong>{{ $errors->first('flight_destination') }}</strong>
                                                </span>
                                            @endif 
                            </div>
                            
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <button type="submit" class="btn btn-primary">
                                Submit
                                </button>
                                <a href="{{ url('admin-flightSource') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
                
                
                
            </div>
            
            <!--end::Portlet-->
            
        </div>
    </div>
</div>
@endsection
@section('bottom_script')
<script src="{{ asset('assets/demo/default/custom/components/datatables/base/html-table.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/custom.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/flightDestination/edit.blade.php
@extends('adminlayouts.dashMaster')
@section('title') Admin | Edit Flights Destination @endsection
@section('style')
@endsection
@section('content')
<meta name="csrf_token"  content="{{ csrf_token() }}" />
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                Edit Flight Destination
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Edit Flight Destination
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
      
        <div class="row">
            <div class="col-md-6">
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    
                    <!--begin::Form-->
                    {{ Form::model($flight, array('route' => array('admin-flightDestination.update', $flight->id), 'method' => 'PUT' , 'class' => 'm-form m-form--fit m-form--label-align-right' )) }}
                    <div class="m-portlet__body">
                        <input type="hidden" name="_token" id="_token" value="{{csrf_token()}}">
                        <div class="form-group m-form__group">
                            <label for="exampleInputEmail1">
                                Flight Destination Name<span class="m--font-danger"> *</span>

                            </label>
                            
                            <input type="text" class="form-control m-input" autocomplete="off" id="exampleInputText" value="{{$flight->flight_destination}}" name="flight_destination"  placeholder="Enter Flight Name">
                            @if ($errors->has('flight_destination'))
                                                <span class="help-block text-danger">
                                                    <strong>{{ $errors->first('flight_destination') }}</strong>
                                                </span>
                                            @endif 
                        </div>
                        
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="submit" class="btn btn-primary">
                            Submit
                            </button>
                          <a href="{{ url('admin-flightSource') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </div>
                    {!! Form::close(); !!}
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
                
                
                
            </div>
            
            <!--end::Portlet-->
            
        </div>
    </div>
</div>
@endsection
@section('bottom_script')
<script src="{{ asset('assets/demo/default/custom/components/datatables/base/html-table.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/custom.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/flightDestination/index.blade.php
@extends('adminlayouts.dashMaster')
@section('title') Admin | Flights Destination @endsection
@section('style')
<style type="text/css">
.btn.m-btn--hover-accent.active, .btn.m-btn--hover-accent:active, .btn.m-btn--hover-accent:focus, .btn.m-btn--hover-accent:hover, .show>.btn.m-btn--hover-accent.dropdown-toggle {
border-color: #5767de!important;
color: #fff!important;
background-color: #5767de!important;
}
</style>
@endsection
@section('content')
<meta name="csrf_token"  content="{{ csrf_token() }}" />
<input type="hidden" name="_token" id="_token" value="{{csrf_token()}}">
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                Flight Destination
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Flight Destination
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
        @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
        <div class="m-portlet m-portlet--mobile">
           
            <div class="m-portlet__body">
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                            <div class="row align-items-center">
                                <div class="col-xl-8 order-2 order-xl-1">
                                    <div class="form-group m-form__group row align-items-center">
                                        <div class="col-md-4">
                                            <div class="m-input-icon m-input-icon--left">
                                                <input type="text" class="form-control m-input m-input--solid" placeholder="Search..." id="m_form_search">
                                                <span class="m-input-icon__icon m-input-icon__icon--left">
															<span>
																<i class="la la-search"></i>
															</span>
														</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                     <a href="{{route('admin-flightDestination.create')}}" class="btn m-btn--pill    btn-primary" >Add New</a>
                                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                                </div>
                             </div>
                        </div>
                
                <!--begin: Datatable -->
                <table class="m-datatable" id="html_table" width="100%">
                    <thead>
                        <tr>
                            <th>Sr No</th>
                            
                            <th>Flight Destination Name</th>
                            <th>Status</th>
                            <th>Actions</th>
                            <th>Action</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 1; ?>
                        @foreach($flight as $flights)
                        
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{$flights->flight_destination}}</td>
                            <td>
                                @if($flights->status == 0)
                                {{'<span><span class="m-badge  m-badge--danger m-badge--wide">Deactivated</span></span>'}}
                                @else
                                {{'<span><span class="m-badge  m-badge--primary m-badge--wide">Activated</span></span>'}}
                                @endif
                            </td>
                            <td>
                                 {{'<a href="'.route('admin-flightDestination.edit',$flights->id).'" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit "><i class="la la-edit"></i></a>'}}
<<<<<<< HEAD
                                 {{'<a href="'.url('flightDestinationIsDelete').'/'.$flights->id.'/0"  class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Delete " onclick="return deletemsg('.$flights->id.');" ><i class="la la-trash-o"></i></a>'}}
=======
                                 {{'<a href="'.url('flightDestinationIsDelete').'/'.$flights->id.'/0" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Delete " ><i class="la la-trash-o"></i></a>'}}
>>>>>>> a4c94b4ecea0498d6873d20ed433a1495e86c9dc
                            </td>
                            <td>
                                @if($flights->status == 0)
                                {{'<a href="'.url('flightDestinationStatus').'/'.$flights->id.'/1" class="btn m-btn--pill    btn-primary" >Active</a>'}}
                                @else
                                {{'<a href="'.url('flightDestinationStatus').'/'.$flights->id.'/0" class="btn m-btn--pill    btn-danger" >Block</a>'}}
                                @endif
                            </td>

                        </tr>

                        @endforeach
                    </tbody>
                </table>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
</div>
@endsection
@section('bottom_script')
<script src="{{ asset('assets/demo/default/custom/components/datatables/base/html-table.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/custom.js') }}" type="text/javascript"></script>
<script>
    function deletemsg(id) {
        swal({
            title: 'Are you sure?',
            text: "Are you sure you wish to delete ",
            showCancelButton: true,
            confirmButtonColor: '#34bfa3',
            cancelButtonColor: '#f4516c',
            confirmButtonText: 'Confirm'
        }).then((result) => {
            if(result.value)
        {
            {{--alert("{{url('cityIsDelete')}}/"+id);--}}
                window.location= "{{url('flightDestinationIsDelete')}}/"+id+'/0';
            return true;
        }
    else
        {return false;
        }
    }
    );
        return false;
    }

</script>
@endsection